# Generated by Django 4.2.6 on 2023-10-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobiles', models.CharField(max_length=121)),
                ('price', models.CharField(max_length=121)),
                ('ram', models.CharField(max_length=121)),
                ('storage', models.CharField(max_length=121)),
            ],
        ),
    ]
