# Generated by Django 4.2.6 on 2023-10-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=121)),
                ('locality', models.CharField(max_length=121)),
                ('mobile', models.IntegerField()),
                ('city', models.CharField(max_length=1212)),
                ('state', models.CharField(max_length=121)),
                ('zipcode', models.IntegerField()),
            ],
        ),
    ]
